/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsMisTicketsRouteImport } from './routes/tickets/mis-tickets'
import { Route as AdminCatalogsIndexRouteImport } from './routes/admin/catalogs/index'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsMisTicketsRoute = TicketsMisTicketsRouteImport.update({
  id: '/tickets/mis-tickets',
  path: '/tickets/mis-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogsIndexRoute = AdminCatalogsIndexRouteImport.update({
  id: '/admin/catalogs/',
  path: '/admin/catalogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/admin/tickets/$ticketId',
  path: '/admin/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tickets/mis-tickets': typeof TicketsMisTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/catalogs/': typeof AdminCatalogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tickets/mis-tickets': typeof TicketsMisTicketsRoute
  '/admin': typeof AdminIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/catalogs': typeof AdminCatalogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tickets/mis-tickets': typeof TicketsMisTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/catalogs/': typeof AdminCatalogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/tickets/mis-tickets'
    | '/admin/'
    | '/tickets/'
    | '/admin/tickets/$ticketId'
    | '/admin/catalogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/tickets/mis-tickets'
    | '/admin'
    | '/tickets'
    | '/admin/tickets/$ticketId'
    | '/admin/catalogs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/tickets/mis-tickets'
    | '/admin/'
    | '/tickets/'
    | '/admin/tickets/$ticketId'
    | '/admin/catalogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TicketsMisTicketsRoute: typeof TicketsMisTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
  AdminCatalogsIndexRoute: typeof AdminCatalogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/mis-tickets': {
      id: '/tickets/mis-tickets'
      path: '/tickets/mis-tickets'
      fullPath: '/tickets/mis-tickets'
      preLoaderRoute: typeof TicketsMisTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogs/': {
      id: '/admin/catalogs/'
      path: '/admin/catalogs'
      fullPath: '/admin/catalogs/'
      preLoaderRoute: typeof AdminCatalogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/admin/tickets/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TicketsMisTicketsRoute: TicketsMisTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
  AdminCatalogsIndexRoute: AdminCatalogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
